---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secret
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_SECRET_KEY: AgCZ/ig5yHkWGRkcBudTxG7QHT0MGJ/jZtIX24vTVp0N316RZmdaz3ip0HOtaKeh7/i2w5+an5oAvZOVWFJSqMnjeWPxxqIIWVDeRr8y7pPKjGx0t17NsKG6eBHKE0c1FpWP+BJUC65kqXuKIhbXObQEqGh10AKuDUeaZjkJekLvSWtO5EODcJgvmOddqgKs2C/ZWCEDCbqji8rCs4maPrsoNhehTMNlAX9ecXZabYLrICqrVbngb/CwUql1z24olNBVbibVcbHrrn3rwMcWviK6BBplbgDa07ynpFJ/WnjZ06i4xdAkfzhJELDIbaEyrdv+GYrGTGXBxpT239gEuZyTvy3cXaM2mQsfx94YaoY6mHiPl/88ftPBTHXsdl5tghx47s/f4NkaptDpUcPJY6bSdarJUyRgr1ekbHZNAoIKhvM4OrqWVIwLXpaw6ZTK55/aIUfeTgyma4fPQ+viS4fJ+qEYTS2iik30r8MDLNRi2BsU4anEyXxMNcyyj5dzIiJt4AWS4MqvEKp2OYfw4FO7TYRMnkgqvwmEnmFN93KztHCXQo2xUppGUKR4gPk0hLr3YQjnAHlGIspFdrldwnuaKAfHx6aC8GU5R4Vn49XmSECpfZpFkfJ5A+KylYepaGBHW5ww6V0BR+MOQrd1b/nYQW+A6HzNTuRs7t3BQDi6nkeO0A1XdB6npQOES/fCpm5FoV7y+MDXKeG5/cZl+SE3SFU13OblmLlj2GinL03L2/Ga+YkrVF3c4kxOlLpwU7cdSrK1ilsdmQqkLOB5ilvG
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secret
      namespace: authentik
    type: Opaque
