authentik:
  # Config globale d'Authentik
  authentik:
    existingSecret: "authentik-secret"
    error_reporting:
      enabled: false

  # On bride le serveur pour pas faire fumer tes 16 Go de RAM
  server:
    resources:
      limits:
        memory: "350Mi"
      requests:
        memory: "150Mi"

  # On bride le worker en arrière-plan
  worker:
    resources:
      limits:
        memory: "350Mi"
      requests:
        memory: "150Mi"

  # Base de données Postgres intégrée et bridée
  postgresql:
    enabled: true
    postgresqlResources:
      limits:
        memory: "256Mi"
    persistence:
      enabled: true
      size: 5Gi

  # Cache Redis intégré et bridé
  redis:
    enabled: true
    resources:
      limits:
        memory: "128Mi"
