global:
  envFrom:
    - secretRef:
        name: authentik-secret

authentik:
  authentik:
    error_reporting:
      enabled: false

  server:
    resources:
      limits:
        memory: "350Mi"
      requests:
        memory: "150Mi"

  worker:
    resources:
      limits:
        memory: "350Mi"
      requests:
        memory: "150Mi"

  postgresql:
    enabled: true
    postgresqlResources:
      limits:
        memory: "256Mi"
    persistence:
      enabled: true
      size: 5Gi

  redis:
    enabled: true
    resources:
      limits:
        memory: "128Mi"
