---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secret
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_SECRET_KEY: AgBUgJvBCxJFStYoUwavOxmGA/G5a9OFzwzmyr2j+7Vh6NP9nrwd2NDrWR1LwEtQ1DwL6F+etfQlJ8/jxlFSO4nc29ocoK7uGRi1diDo67OjVW6vWiOcko6lgIwsinlJfdO+ORg6oy0SYdsWQkcETuS7MGwaVX0jJp2jPpEAe92LV7bV3L1AHPmXVlBUl+EWyx7ualzVAvKeyrzK6ALP5/y6wyh2dpv2PFvLfG3gS3DFJe6Bbv/oILg756HvDc6CF9mBK6pDm1pEEJtLE/65vYplDVeVEs0n/cFkrR9JpIyE2uNkYysOUEOIdRjpiPT01ddKVic0yWs8+oFdAvgKiev01iunsodQQ5pIwDBmhBvC1UBfXUlj0dqV1Yxi62qeix+o4dwNkPvtmhA8IxBykT8EMEZ96SGLg3UeanoNyjhkI8hY2AEkEDa1+JBa3EoHImrz7xtwvrLHHyaFvM7v4g3q0y3WomK5p4LP5ltQT/RpENovPPSwRHZEFOy2akpUH/lDnObEYvakj0XxCNcHMfhGVF/zN8K4Z6C9FXOead+Tcq5wWlJGyJq34vNt7xTodZUCh68vBxkjkAUiCjJ/re3oDrix9t03gnIXY3kXucBLUkJ0IT6Y79oQ/xOAAed8DHbDst0a9a7Ez98FrUsN9d7A74CFuJzWb4yWi47H1UttqM6ZOVG4zxlDMOmgLRnEC1rC7Wa22FQku5umJGHE+/oc+Gxl
    POSTGRES_PASSWORD: AgAAMxLpfghryuYFz5wrw8g6/G/ryGBXOtrSvYr4BzWmvip+C/u1uxCrQiYj7boQz1WUHxbYPtBdTaoxcHVQNXuqjDctuQN1b+aJOkI/Gcgetu/dTXmB09JoH4E98Srtc77IlRoSoTD+uRU1F2nKrVdnZWKVktnFa02un7NNrCIZoN6mSE0lbbHIPge6VfmtaB3blyegAeGbd05ys5VyYjQjG1M4Zhc6uCis/KVwT2k54KiYOkTsriNm3Gx57BcyTHaFdXl/T+QV6fezyTO6Kd1IOs3br/ueeeaj6+c+FDbBWByk/zjALMeGYHFeKxCv0tCHN+dChbMynPwLAdtxO+CYkrKwtUEhk1pWGl1S0yo7hnjRvGCTlIdGHBi7h1Mljn8h+zoUhyX14dQG5S5gR+vrse/HKLTzoA4udU4qhRJtxhrM+G89tKzrsnVfs5atQPMvOWKQELYDoLf0Zxkc1034BEIS+lVGxr9K2ztAgN/3rqSTxOC972G5PLIGrhaQZiPxw8eZMVZCcs15p4mENA5fc+u3Hew+yruBDpvSLT6fMMmz2yPgGbZHKJtTSX9gRLj760f4OYn1q5qvOE+KGiHs6yFTnRAN5FzNqkoP4NrK+CxZyl2rVD0dWO+ypH9ap6VPG4R6yxMLAgL5SvKwkF1zJbO1E7j1nohAAx5YJ04jRXK9YHCZFldxEccRpjUHqVXS3kvo62UeB5M1pSA=
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secret
      namespace: authentik
