---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secret
  namespace: authentik
spec:
  encryptedData:
    secret_key: AgCfrq7xKpDMHJlLoth+DE0Ik8CN9NwfUGatCvhzr9lLA2+RnO9ZhbieKl4ARX06wSwC/oXQPoF60ScHa4sT1xtps+014Zbt0NcyZK1hrB2qCgDNGFXYQfx11aNzRxuDUnThBi6BKkGtW59m+WIJ6mbj3T88zak2fzaramGI2UpImImJrMixcLkCb+59y8s2wsswSlOebYW0nA1JLcGHAK4Czcp0BQFmut0dcd26+sIBfTBXc9EB59X+GFNYlpI8Sv9ek3ydeb/TD8DVLHF6rlEpZHRPoQZuMPnPrVdvadWeylNxgZwTQgF0UMnrOTgYMhsoroFbDskvBrPP77Jl9p3F1kh16SLzOnMt8Fo2lH+m1GLfiWZMTxjQp7ziWnW/Y2XAFx/zOv0QzGy7UwPJQM1wd1kj9jJRh0UBcjHwonVURbHygocarfZiAgmLT42lBUfw9ORlO/CAsvl/SCfvc3NomyDiO+08n2wh009xHP6QhohLRgGZw6QIMk9MfoL+hfgqWs/LCuiAUxKOH8ZcwuCYt0VDSyizZLYU7wGaK7ZtRchJPjBM28TS8w+8a22TxTYUXZRSTstkYjBUz7Up4xgzqWEwYjVyVaPkN0vpeNV19BEDn+/CB2q/WUHz5fPszOQ7PhfqGtNNnXAzUIGSG085g4ZgTzIAi583R4gD6bLMi/HLQBSDy3yHKQTuoMLDgLXbfOtwO8r14RxS0Y/xnrChIZA29mScWo0jd8RgzHqgleAQspHv9fjorkWg6SfoApFxq0GkB4p82zUor1ik3XtG0G/bCsU=
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secret
      namespace: authentik
