apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-config
  namespace: forgejo
data:
  FORGEJO____APP_NAME: "Gitbaz"
  FORGEJO____APP_SLOGAN: "Git good or get rekt"

  FORGEJO__SERVICE__ENABLE_CAPTCHA: "true"
  FORGEJO__SERVICE__REQUIRE_EXTERNAL_REGISTRATION_CAPTCHA: "true"

  FORGEJO__SERVER__ROOT_URL: "https://git.kelbaz.dev"
