apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-ingress
  namespace: ai-kelbaz
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - ai.kelbaz.dev
    secretName: ai-kelbaz-tls 
  rules:
  - host: ai.kelbaz.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: llama-service
            port:
              number: 80
