apiVersion: apps/v1
kind: Deployment
metadata:
  name: seukai-bot
  namespace: seukai-bot
  labels:
    app: seukai-bot
  annotations:
    argocd-image-updater.argoproj.io/image-list: seukai-bot=ghcr.io/kelbazz/seukai-bot
    argocd-image-updater.argoproj.io/seukai-bot.update-strategy: latest
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: seukai-bot
  template:
    metadata:
      labels:
        app: seukai-bot
    spec:
      imagePullSecrets:
        - name: ghcr-kelbaz-secret
      containers:
        - name: seukai-bot
          image: ghcr.io/kelbazz/seukai-bot:latest
          imagePullPolicy: Always
          args: ["deno", "task", "start"]
          envFrom:
            - configMapRef:
                name: seukai-bot-config
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: seukai-bot-secrets
                  key: TOKEN
          volumeMounts:
            - name: bot-data
              mountPath: /app/data
      volumes:
        - name: bot-data
          persistentVolumeClaim:
            claimName: bot-data-pvc
