---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-kelbaz-secret
  namespace: seukai-bot
spec:
  encryptedData:
    .dockerconfigjson: AgAssvrID1+dVfuAeYIhPqB4CmGNSEWIB8Jyl/drqhGvGtB5KOKaJWeNqEiCNvpsbjQYeYXoCBer32uyGya4rk9OjaDBazU6K5XGGZfLptJrdvhOs7XKTjvZUOODVfamBh3UV3iOoxqtxkVlWZMGipr6j0hTgXlcbt8Bd1errdamgTfyJCCszfDix9nRFqtNo9hAiiLQBgoXNxOBemLOAG/nDnyeNnRS/B8pxqdAE1g2i1U3nqjSuRB5+7aPru8K6gqwx+jKrGaZ+opDlHLhvca2pQ5aJ1ffNGHlZ2UyV7IkWQrSbAj7Av2SHdM5Fmb9gU9AQeKCVQxhEhDilCemedKkEZstlX6hNzs4ohi4zsBRZpit/d6q1+ceGeIUjfJtEzu0c+wA+Mt8Ovzzp1NzpYZ8fo6ppelR6SgfcUPh8sunlmYRds9kdaSxX2aPyeyJVq8s+K+/VqP+a0+T/SbX8F/zkzotf5zByYrt0dhsd+KDgvgpOv/f8HH+SgNx6udAWc+lPSZuP+SRdO6fA6tutQ5Ahudvc19gtmR3Oh18Us5o/KtLgg9Qr4IS/2ViuA2tlVG1ayX/7pwsA26WqH77drJaVfdeHCU016bcnKAGsUngB2lZjTh2HNa3O435sE5m1p5Os0j9vkDE4ZXwkkywoYPDJAZpmcgO6jVYvqmbnxpzgbruR8ovr8Ym8tIgPyJ+zkC/xdyCiY5OFCzKMrx9ReEm4j54ryk2ZI61N9xsrFlM+wlc7zVL6mdcPRxMYI2pOfl6Sbq/QaEvWRIOmkB5G6XDtI9A3LG+hPNTTkGOL/PaGYSzuwjAkVNjzHf8Kg0lJAJPGNhp8S70Ld1eeSPy6Yh2S9uYoZO+JEfJhaaQ/c+P/Txjj3qrlV6weAXz+N7/fay7BqNb39sX0v7biBeI2plhJsCR7StMSLfsFYrg
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-kelbaz-secret
      namespace: seukai-bot
    type: kubernetes.io/dockerconfigjson
