---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: seukai-bot-secrets
  namespace: seukai-bot
spec:
  encryptedData:
    TOKEN: AgCS+bSvSMj3DSWy13hscjikUHw/NWjhlDspVjwI3Kn4SyLBKBmWbAEr00GPZVenqjETdDx/k3YlKFw/IVgEqIGwNBoJihbMHC//Vdigw9vK6iNXt32hlgGWDimyn9vVmfMP80alc3LZNRus0RUX0zTax0nK6Pe6PlfT/TGmp4xB+yd8fOIZBLHX7DIymb7lOAoJaMHj1Rjqm8iari59yy8WUx6fMNPorjnWkuu9AKYd1/a6GgZ76L+MimeFg95szq+wUjCF7oKLT6y4Dfl8Ujm1RVQGWMmmFzeLYT9GRtp8IW75wEiFp27kXmpsgyrdV7OgVPW0f1rlRwf2REe+ELh1z8eH68ni6Em7atPnXE9uwtDLFEs9AZGMGnzO6p22JEHAb6r8ZjsbGte6ent2msVPowO+GWCGoeHNOgTd3sxwM4rIPNQfO6eTCt6d/WIoRBv/Fovk09PSroJiKepxZ66IvATHqd4GLXBywezQSi3dOCqi3WeJJWon+XsVyoAIaIF1HkMlvaYuo23JMtZIYCHgsQmF5J6VLoJnMBorb/alYGYW0YnuTFEzy7kI/KEIKQshJ8mBxtpJSWOtPsWa6g2iE0zJ+TWDOGd9qaBum6XhX5SkJVrH2hR/xfB4xTbheRNhmn/oJbatWRaci0FUoPYUMtZKKrXKX/NB0wubfQqXvLa62dBczgf74koUyRPUU8JwkXgBWX4EuBd4bdkQ7AcDBIo5FvOoUuEiYi1ps0+w++2CqC6dUii1QEmRvU9etcQsF1uaEm9a6iQ2im6yg3pJp8QU979ZPQo=
  template:
    metadata:
      creationTimestamp: null
      name: seukai-bot-secrets
      namespace: seukai-bot
